export const ROUTES = {
  root: '/',
  universe: '/universe',
  library: '/library',
  libraryHome: (libraryId: string) => `/library/${libraryId}`,
  libraryPractice: (libraryId: string) => `/library/${libraryId}/practice`,
  treeNew: (libraryId: string) => `/library/${libraryId}/trees/new`,
  tree: (libraryId: string, treeId: string) => `/library/${libraryId}/tree/${treeId}`,
  treePath: (libraryId: string, treeId: string) => `/library/${libraryId}/tree/${treeId}/path`,
  treeVerify: (libraryId: string, treeId: string) => `/library/${libraryId}/tree/${treeId}/verify`,
  // Compatibility URLs. Product navigation uses path / verify.
  treeLearn: (libraryId: string, treeId: string) => `/library/${libraryId}/tree/${treeId}/learn`,
  treePractice: (libraryId: string, treeId: string) => `/library/${libraryId}/tree/${treeId}/practice`,
  treePracticeSession: (libraryId: string, treeId: string) => `/library/${libraryId}/tree/${treeId}/practice/session`,
  pointStudy: (libraryId: string, treeId: string, pointId: string) => `/library/${libraryId}/tree/${treeId}/point/${pointId}/study`,
  pointTeach: (libraryId: string, treeId: string, pointId: string) => `/library/${libraryId}/tree/${treeId}/point/${pointId}/teach`,
  pointVerify: (libraryId: string, treeId: string, pointId: string) => `/library/${libraryId}/tree/${treeId}/point/${pointId}/verify`,
  // Compatibility URLs for pre-V11 history.
  pointLearn: (libraryId: string, treeId: string, pointId: string) => `/library/${libraryId}/tree/${treeId}/point/${pointId}/learn`,
  pointPractice: (libraryId: string, treeId: string, pointId: string) => `/library/${libraryId}/tree/${treeId}/point/${pointId}/practice`,
  treeEdit: (libraryId: string, treeId: string, section = 'structure') => `/library/${libraryId}/tree/${treeId}/edit/${section}`,
  pointNewContent: (libraryId: string, treeId: string) => `/library/${libraryId}/tree/${treeId}/points/new/content`,
  pointNewPlace: (libraryId: string, treeId: string) => `/library/${libraryId}/tree/${treeId}/points/new/place`,
  progress: '/progress',
  legacyTeachUnit: (unitId: string) => `/teach/${unitId}`,
  legacyPracticeSession: (sessionId: string) => `/practice/session/${sessionId}`,
} as const;
